gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - config.rb
  - bower.json
  - package.json
  - Gruntfile.js

defaults:
  - scope:
      path: "releases/"
      type: pages
    values:
      layout: "release"
  - scope:
      path: "news"
    values:
      layout: "default"
      category: "news"

markdown: kramdown

kramdown:
  input: kramdown
  hard_wrap: false
