exclude:
  - Gemfile
  - Gemfile.lock
  - config.rb
  - bower.json
  - package.json
  - Gruntfile.js

lenskit:
  version: 2.0.5
  prerelease: 2.1-M4
  next: 2.1
  downloadUrl: http://files.grouplens.org/lenskit

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
