exclude:
  - Gemfile
  - Gemfile.lock
  - config.rb
  - bower.json

defaults:
  - scope:
      path: "releases/"
      type: pages
    values:
      layout: "release"
  - scope:
      path: "documentation"
      type: pages
    values:
      layout: "default"
      sidenav: doc-nav.html
  - scope:
      path: "news"
    values:
      layout: "default"
      category: "news"

markdown: kramdown

kramdown:
  input: kramdown
  hard_wrap: false
